# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvmamaios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_branch',
            field=models.CharField(default='master', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(default='Unknow', max_length=50),
        ),
    ]
