# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvmamaios', '0002_auto_20170601_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
