# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvmamaios', '0003_auto_20170601_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_status',
            field=models.CharField(default='Unknow', max_length=50),
        ),
        migrations.AlterField(
            model_name='checkstep',
            name='step_status',
            field=models.CharField(default='Unknow', max_length=50),
        ),
    ]
