# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-02 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvmamaios', '0004_auto_20170601_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkstep',
            name='step_duration',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
    ]
