# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvmamaios', '0006_auto_20170604_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkstep',
            name='step_duration',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True),
        ),
    ]
