# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lvmamaios', '0007_auto_20170604_1251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
