# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvmamaios', '0008_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkstep',
            name='step_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
