# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvmamaios', '0011_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='log',
            field=models.TextField(default=''),
        ),
    ]
