# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lvmamaios', '0012_report_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_status', models.CharField(default='unknow', max_length=50)),
                ('step_action', models.CharField(default='', max_length=50)),
                ('step_description', models.TextField()),
                ('step_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(default='', max_length=50)),
                ('version_number', models.CharField(default='', max_length=50)),
                ('publish_date', models.DateTimeField(auto_now=True)),
                ('publish_people', models.CharField(default='unknow', max_length=50)),
                ('commitid', models.CharField(default='', max_length=50)),
                ('committer', models.CharField(default='', max_length=50)),
                ('commit_message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='checkstep',
            name='report',
        ),
        migrations.RemoveField(
            model_name='report',
            name='author',
        ),
        migrations.RemoveField(
            model_name='report',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_branch',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_status',
        ),
        migrations.AddField(
            model_name='project',
            name='develop_branch',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_rc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='CheckStep',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AddField(
            model_name='version',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lvmamaios.Project'),
        ),
        migrations.AddField(
            model_name='publishstep',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lvmamaios.Version'),
        ),
    ]
