# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvmamaios', '0013_auto_20170614_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='latest_version_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='latest_version_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='latest_version_publish_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='latest_version_publish_people',
            field=models.CharField(default='unknow', max_length=50),
        ),
    ]
