# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvmamaios', '0014_auto_20170614_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='latest_version_publish_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='latest_version_publish_people',
            field=models.CharField(default='', max_length=50),
        ),
    ]
