# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvmamaios', '0015_auto_20170614_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='latest_version_publish_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
