# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvmamaios', '0019_auto_20170615_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='is_end',
            field=models.BooleanField(default=True),
        ),
    ]
