# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvmamaios', '0020_version_is_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_end',
            field=models.BooleanField(default=False),
        ),
    ]
