# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvmamaios', '0021_auto_20170615_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='is_end',
        ),
        migrations.AddField(
            model_name='version',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
