# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-16 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lvmamaios', '0022_auto_20170615_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50)),
                ('app_url', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50)),
                ('module_version', models.CharField(max_length=50)),
                ('is_rc', models.BooleanField(default=False)),
                ('module_assignee', models.CharField(max_length=50)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lvmamaios.App')),
            ],
        ),
    ]
