# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-16 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lvmamaios', '0024_app_app_version'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Version',
            new_name='ModuleVersion',
        ),
    ]
