# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-16 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lvmamaios', '0025_auto_20170616_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_version', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='app',
            name='app_version',
        ),
        migrations.RemoveField(
            model_name='module',
            name='app',
        ),
        migrations.AddField(
            model_name='appversion',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lvmamaios.App'),
        ),
        migrations.AddField(
            model_name='module',
            name='appversion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lvmamaios.AppVersion'),
        ),
    ]
