# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-16 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvmamaios', '0026_auto_20170616_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='is_rc',
            field=models.BooleanField(default=False),
        ),
    ]
